<Window x:Class="MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
   Title="Cadastro de Clientes" Height="455" Width="578">
    <Grid>
        <Grid.Resources>
            <DataTemplate x:Key="ClientesListaTemplate">
                <Grid ShowGridLines="True">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="120" />
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="16" />
                    </Grid.RowDefinitions>
                    <TextBlock Text="{Binding nome}" Grid.Column="0" Grid.Row="0" />
                </Grid>
            </DataTemplate>
        </Grid.Resources>
        <Grid Name="grid1" Margin="193,12,0,0" Height="314" VerticalAlignment="Top">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="121*" />
                <ColumnDefinition Width="239*" />
            </Grid.ColumnDefinitions>
       <!-- Define as Labels e os TextBox -->
            <Label Height="28" Name="label1" VerticalAlignment="Top" HorizontalAlignment="Left" Width="93" Content="Código :"></Label>
            <TextBox Text="{Binding id,Mode=OneWay}" Grid.Column="1" Height="23" Name="textBox1" VerticalAlignment="Top" Margin="0,0,8,0" Background="WhiteSmoke" />
            <Label Margin="0,26,0,260" Name="label2" HorizontalAlignment="Left" Width="93" Content="Nome :"></Label>
            <TextBox x:Name="textBox2" Grid.Row="0" Grid.Column="1" Text="{Binding UpdateSourceTrigger=LostFocus, Path=nome}" 
                     Margin="0,28,8,0" Height="23" VerticalAlignment="Top" />
            <TextBox Text="{Binding nascimento,StringFormat=\{0:dd/MM/yyyy\}}" Grid.Column="1" Margin="0,56,8,0" Name="textBox3" Height="23" VerticalAlignment="Top" />
            <Label Name="label3" Margin="0,54,0,0" Height="24" VerticalAlignment="Top" HorizontalAlignment="Left" Width="93" Content="Nascimento:"></Label>
            <Label Margin="0,82,0,0" Name="label4" Height="24" VerticalAlignment="Top" HorizontalAlignment="Left" Width="93" Content="Endereço :"></Label>
            <TextBox Text="{Binding endereco}" Grid.Column="1" Margin="0,84,8,0" Name="textBox4" Height="23" VerticalAlignment="Top" />
            <Label Height="24" Margin="0,110,0,0" Name="label5" VerticalAlignment="Top" HorizontalAlignment="Left" Width="93" Content="Email :"></Label>
            <TextBox Text="{Binding email}" Grid.Column="1" Height="23" Margin="0,112,8,0" Name="textBox5" VerticalAlignment="Top" />
            <Label Height="24" Margin="0,138,0,0" Name="label6" VerticalAlignment="Top" HorizontalAlignment="Left" Width="93" Content="Cep :"></Label>
            <TextBox Text="{Binding cep}" Grid.Column="1" Height="23" Margin="0,140,8,0" Name="textBox6" VerticalAlignment="Top" />
            <Label Height="24" Margin="0,166,0,0" Name="label7" VerticalAlignment="Top" HorizontalAlignment="Left" Width="93" Content="Cidade :"></Label>
            <TextBox Text="{Binding cidade}" Height="23" Margin="0,168,8,0" Name="textBox7" VerticalAlignment="Top" Grid.Column="1" />
            <Label Height="24" Margin="0,194,0,0" Name="label8" VerticalAlignment="Top" HorizontalAlignment="Left" Width="90" Content="Celular :"></Label>
            <TextBox Text="{Binding celular}" Height="23" Margin="0,196,8,0" Name="textBox8" VerticalAlignment="Top" Grid.Column="1" />
            <Label Height="24" Margin="0,222,0,0" Name="label9" VerticalAlignment="Top" HorizontalAlignment="Left" Width="90" Content="Contato :"></Label>
            <TextBox Text="{Binding telefone}" Height="23" Margin="0,224,8,0" Name="textBox9" VerticalAlignment="Top" Grid.Column="1" />
            <Label Height="24" Margin="0,250,0,0" Name="label10" VerticalAlignment="Top" HorizontalAlignment="Left" Width="90">E-mail:</Label>
            <TextBox Text="{Binding contato}" Height="23" Margin="0,252,8,0" Name="textBox10" VerticalAlignment="Top" Grid.Column="1" />
            <Label Height="24" Margin="0,278,0,0" Name="label11" VerticalAlignment="Top" HorizontalAlignment="Left" Width="90" Content="Obs:"></Label>
            <TextBox Text="{Binding obs}" Height="23" Margin="0,280,8,0" Name="textBox11" VerticalAlignment="Top" Grid.Column="1" />
        </Grid>
        <!-- Define os Anterior e Proximo e os eventos-->
        <Button Margin="193,342,0,0" Name="btnAnterior" Click="btnAnterior_Click" Height="24" VerticalAlignment="Top" HorizontalAlignment="Left" Width="108" 
Content="&lt; Anterior"></Button>
        <Button Margin="0,342,12,0" Name="btnProximo" HorizontalAlignment="Right" Width="108" Click="btnProximo_Click" Height="24" VerticalAlignment="Top" 
Content="Próximo &gt;"></Button>
        <!-- Define o ListBox e vincula a propriedade DataContext-->
        <ListBox IsSynchronizedWithCurrentItem="True" ItemsSource="{Binding}" ItemTemplate="{StaticResource ClientesListaTemplate}" 
Name="clientesListBox" HorizontalAlignment="Left" Width="180" Margin="9,12,0,10" ForceCursor="True" Foreground="Yellow" FontSize="14" DataContext="{Binding}">
            <ListBox.Background>
                <LinearGradientBrush EndPoint="1,0.5" StartPoint="0,0.5">
                    <GradientStop Color="Black" Offset="0" />
                    <GradientStop Color="#00B3EBB7" Offset="1" />
                </LinearGradientBrush>
            </ListBox.Background>
        </ListBox>
        <!-- Define os botões Salvar,Novo e Excluir e os eventos-->
        <Button Height="23" Margin="193,382,0,0" Name="btnSalvar" VerticalAlignment="Top" Click="btnSalvar_Click" HorizontalAlignment="Left" Width="108" 
Content="Salvar"></Button>
        <Button Height="23" HorizontalAlignment="Left" Margin="314,382,0,0" Name="btnNovo" VerticalAlignment="Top" Width="108" Click="btnNovo_Click" 
Content="Novo"></Button>
        <Button Height="23" HorizontalAlignment="Left" Margin="437,382,0,0" Name="btnExcluir" VerticalAlignment="Top" Width="108" Click="btnExcluir_Click" 
Content="Excluir"></Button>
        <Button Content="Encerrar" Height="27" HorizontalAlignment="Left" Margin="315,341,0,0" Name="btnSair" VerticalAlignment="Top" Width="107" />
        <Grid.Background>
            <LinearGradientBrush EndPoint="1,0.5" StartPoint="0,0.5">
                <GradientStop Color="Transparent" Offset="0" />
                <GradientStop Color="Black" Offset="1" />
            </LinearGradientBrush>
        </Grid.Background>
    </Grid>
</Window>
